import { Inter } from "next/font/google";
import "./app.scss";
import Header from "./components/Header";
import Sidebar from "./components/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Administrator",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <section className="body">
          <Sidebar />
          <section className="contents">
            {children}
          </section>
        </section>
      </body>
    </html>
  );
}
